name: water
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.3.2
  firebase_core: ^2.4.0
  firebase_database: ^10.0.1
  firebase_storage: ^11.0.8
  wave: ^0.2.2
  flutter_floating_bottom_bar: ^1.2.0
  syncfusion_flutter_charts: ^25.1.35
  provider:
  connectivity_widget:
  fluttertoast: ^8.0.8
  scoped_model: ^2.0.0-nullsafety.0
  flutter_bluetooth_serial_ble:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/707002.gif